directories:
  output: release
  buildResources: build
appId: com.whyself.articlemanager
productName: Blog Article Manager
asar: false
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - node_modules/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
  signAndEditExecutable: false
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
electronVersion: 31.7.7
